<?php

namespace AppBundle\Repository;

/**
 * DoctorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoctorRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Get active doctors
     */
    public function getActiveDoctors($idStatus)
    {
        $query = $this->_em->createQueryBuilder();
        $query->select('doctor.id , doctor.name, doctor.lastname')
            ->from('AppBundle:Doctor', 'doctor')
            ->innerJoin('doctor.status','status')
            ->where('status.id = :idStatus')
            ->setParameter('idStatus', $idStatus);
        return $query->getQuery()->getArrayResult();
    }
}
