<?php

namespace AppBundle\Repository;

/**
 * PatientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatientRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get patient by Parishes
     */
    public function getPatientByParishes($nameParishes)
    {
        $query = $this->_em->createQueryBuilder();
        $query->select('patient.id, patient.historyNumber, patient.registrationDate, patient.gender, patient.birthdate,
        patient.familyDynamics, patient.job, patient.jobDetail,
         personal.name as namePersonal, personal.lastname as lastnamePersonal, 
        personal.secondName as secondNamePersonal, personal.secondLastname as secondLastnamePersonal, personal.document,
        personal.nationality')
            ->from('AppBundle:Patient', 'patient')
            ->leftJoin('patient.personal', 'personal')
            ->innerJoin('patient.place','place')
            ->where('place.name = :nameParishes')
            ->setParameter('nameParishes', $nameParishes);
        return $query->getQuery()->getArrayResult();
    }


    /**
     * Get patient by Document
     */
    public function findPatientByDocument($document)
    {
        $query = $this->_em->createQueryBuilder();
        $query->select('patient')
            ->from('AppBundle:Patient', 'patient')
            ->innerJoin('patient.personal','personal')
            ->where('personal.document = :document')
            ->setParameter('document', $document);
        return $query->getQuery()->getArrayResult();
    }

    /**
     * Get patient by HistoryNumber
     */
    public function findPatientByHistoryNumber($historyNumber)
    {
        $query = $this->_em->createQueryBuilder();
        $query->select('patient')
            ->from('AppBundle:Patient', 'patient')
            ->where('patient.historyNumber = :historyNumber')
            ->setParameter('historyNumber', $historyNumber);
        return $query->getQuery()->getArrayResult();
    }

    /**
     * Get patient by JobStatus
     */
    public function findPatientByJobStatus($job)
    {
        $query = $this->_em->createQueryBuilder();
        $query->select('patient')
            ->from('AppBundle:Patient', 'patient')
            ->where('patient.job = :job')
            ->setParameter('job', $job);
        return $query->getQuery()->getArrayResult();
    }

    /**
     * Get patient of apointment by specialty
     */
    public function getPatientAppointmentsBySpecialty($idSpecialty)
    {
        $query = $this->_em->createQueryBuilder();
        $query->select('DISTINCT  patient.id as patient_id ')
            ->from('AppBundle:Appointment', 'appointment')
            ->leftJoin( 'appointment.patient', 'patient')
            ->innerJoin('appointment.doctor','doctor')
            ->innerJoin('doctor.specialty','specialty')
            ->where('specialty.id = :idSpecialty')
            ->setParameter('idSpecialty', $idSpecialty);
        return $query->getQuery()->getArrayResult();
    }
}
