<?php

namespace AppBundle\Repository;

/**
 * PatientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatientRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get patient by Parishes
     */
    public function getPatientByParishes($nameParishes)
    {
        $query = $this->_em->createQueryBuilder();
        $query->select('patient')
            ->from('AppBundle:Patient', 'patient')
            ->innerJoin('patient.place','place')
            ->where('place.name = :nameParishes')
            ->setParameter('nameParishes', $nameParishes);
        return $query->getQuery()->getArrayResult();
    }

    /**
     * Get patient by Document
     */
    public function findPatientByDocument($document)
    {
        $query = $this->_em->createQueryBuilder();
        $query->select('patient')
            ->from('AppBundle:Patient', 'patient')
            ->where('patient.document = :document')
            ->setParameter('document', $document);
        return $query->getQuery()->getArrayResult();
    }

    /**
     * Get patient by HistoryNumber
     */
    public function findPatientByHistoryNumber($historyNumber)
    {
        $query = $this->_em->createQueryBuilder();
        $query->select('patient')
            ->from('AppBundle:Patient', 'patient')
            ->where('patient.historyNumber = :historyNumber')
            ->setParameter('historyNumber', $historyNumber);
        return $query->getQuery()->getArrayResult();
    }
}
