<?php

namespace AppBundle\Repository;

/**
 * PersonalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonalRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPersonalByDocumentAndNationality($document, $nationality)
    {
        $query = $this->_em->createQueryBuilder();
        $query->select('personal')
            ->from('AppBundle:Personal', 'personal')
            ->where('personal.document = :document')
            ->andWhere('personal.nationality = :nationality')
            ->setParameter('document', $document)
            ->setParameter('nationality', $nationality);
        return $query->getQuery()->getArrayResult();
    }
}
