<?php

namespace AppBundle\Repository;

/**
 * PlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAddressState()
    {
        $query = $this->_em->createQueryBuilder();
        $query->select('place.id', 'place.name')
                ->from('AppBundle:Place', 'place')
                ->where('place.type = :addressType')
                ->setParameter('addressType', 'Estado');
    }

    public function getAddressDistrict($idState)
    {
        $query = $this->_em->createQueryBuilder();
        $query->select('place.id', 'place.name')
                ->from('AppBundle:Place', 'place')
                ->where('place.place = :state')
                ->setParameter('state', $idState);
    }
}
