<?php

namespace AppBundle\Repository;

/**
 * PlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAddressLevel1()
    {
        $query = $this->_em->createQueryBuilder();
        $query = $this->select('place.id', 'place.name')
                ->from('AppBundle:Place', 'place')
                ->innerJoin()
                ->where('place.id = ');
    }
}
