app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#restapi
api_specialty:
   type:     rest
   prefix:   /api/specialty  #importante esto es para construir las urls
   resource: "@AppBundle/Resources/config/api-specialty.yml"

api_status:
   type:     rest
   prefix:   /api/status #importante esto es para construir las urls
   resource: "@AppBundle/Resources/config/api-status.yml"

api_doctor:
   type:     rest
   prefix:   /api/doctor #importante esto es para construir las urls
   resource: "@AppBundle/Resources/config/api-doctor.yml"