security:
    encoders:
        AppBundle\Entity\User: { algorithm: sha512, iterations: 10 }

    role_hierarchy:
        ROLE_PERSONAL:       [ROLE_PERSONAL]
        ROLE_ADMIN: [ROLE_ADMIN]

    providers:
        user:
            entity: { class: AppBundle\Entity\User, property: username }

    firewalls:
        login:
            pattern:   ^/api/login_check
            stateless: true
            anonymous: true
            provider:  user
            form_login:
                check_path: api_login
                require_previous_session: false
                username_parameter: username
                password_parameter: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

#        api:
#            pattern:   ^/api
#            stateless: true
#            provider: user
#            lexik_jwt:
#                authorization_header:
#                    enabled: true
#                    prefix:  Bearer
#                query_parameter:
#                    enabled: true
#                    name:    bearer


    access_control:
        - { path: ^/api/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/api/*, roles: ['ROLE_ADMIN', 'ROLE_PERSONAL'] }